// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbKYl6TIbp0msOU43wJWC5B2tgKTBHpcA',
    appId: '1:1070118193521:web:19f0ca37b746866a0e4ed0',
    messagingSenderId: '1070118193521',
    projectId: 'chat-dce12',
    authDomain: 'chat-dce12.firebaseapp.com',
    storageBucket: 'chat-dce12.appspot.com',
    measurementId: 'G-J6N52LG68K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32GWhwFmKMvdlAyUTeDGxkMu4LGLtuog',
    appId: '1:1070118193521:android:97cef8b7d418da3f0e4ed0',
    messagingSenderId: '1070118193521',
    projectId: 'chat-dce12',
    storageBucket: 'chat-dce12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQd7_QVJbWvf1JZppgYl98meQQffabsk0',
    appId: '1:1070118193521:ios:c101fd34d030b0d50e4ed0',
    messagingSenderId: '1070118193521',
    projectId: 'chat-dce12',
    storageBucket: 'chat-dce12.appspot.com',
    androidClientId: '1070118193521-p692t7p4ia5s8n000r8tofkegq0ug3ii.apps.googleusercontent.com',
    iosClientId: '1070118193521-0joscbrs6al6dmremul463hrmgc6nfub.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQd7_QVJbWvf1JZppgYl98meQQffabsk0',
    appId: '1:1070118193521:ios:c101fd34d030b0d50e4ed0',
    messagingSenderId: '1070118193521',
    projectId: 'chat-dce12',
    storageBucket: 'chat-dce12.appspot.com',
    androidClientId: '1070118193521-p692t7p4ia5s8n000r8tofkegq0ug3ii.apps.googleusercontent.com',
    iosClientId: '1070118193521-0joscbrs6al6dmremul463hrmgc6nfub.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
